=== gifford-lab/seqgra/seqgra/model-config.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="seqgramodel">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="general">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="label" type="xs:string"/>
              <xs:element name="description" type="xs:string"/>
              <xs:element name="library" type="xs:string"/>
              <xs:element name="seed" type="xs:long"/>
              <xs:element name="learner">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="type" type="xs:string"/>
                    <xs:element name="implementation" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="labels">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="label" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="[A-Za-z0-9_-]+"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="metrics">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="metric" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="set" type="xs:string" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="architecture">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="sequential" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="operation" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:anyAttribute processContents="lax"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="hyperparameters" type="hyperparametersType" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="loss" type="hyperparametersType"/>
        <xs:element name="optimizer" type="hyperparametersType"/>
        <xs:element name="trainingprocess" type="hyperparametersType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="hyperparametersType">
    <xs:sequence>
      <xs:element name="hyperparameter" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== gifford-lab/seqgra/docsrc/defs/md/torch-ml2-dna150-conv10-conv10-fc5-s2.xml
<?xml version="1.0" encoding="UTF-8"?>

<seqgramodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://kkrismer.github.io/seqgra/model-config.xsd">
	<general id="torch-ml2-dna150-conv10-conv10-fc5-s2">
		<name>conv layer with 10 11-nt wide filters, conv layer with 10 11-nt wide filters, fully connected layer with 5 units</name>
		<description></description>
		<task>multi-label classification</task>
		<sequencespace>DNA</sequencespace>
		<library>PyTorch</library>
		<inputencoding>1D</inputencoding>
		<labels>
			<label>c1</label>
			<label>c2</label>
		</labels>
		<seed>2</seed>
	</general>
	<architecture>
		<external format="pytorch-module" classname="TorchModel">PyTorch/o2-dna150-conv10-conv10-fc5.py</external>
	</architecture>
	<loss>
		<hyperparameter name="loss">BCEWithLogitsLoss</hyperparameter>
	</loss>
	<optimizer>
		<hyperparameter name="optimizer">SGD</hyperparameter>
		<hyperparameter name="learning_rate">0.001</hyperparameter>
		<hyperparameter name="momentum">0.9</hyperparameter>
	</optimizer>
	<trainingprocess>
		<hyperparameter name="batch_size">32</hyperparameter>
		<hyperparameter name="epochs">100</hyperparameter>
		<hyperparameter name="early_stopping">True</hyperparameter>
		<hyperparameter name="shuffle">True</hyperparameter>
	</trainingprocess>
</seqgramodel>

=== gifford-lab/seqgra/docs/md/tf-mc2-dna150-conv2-lstm32-fc32-s1.xml
<?xml version="1.0" encoding="UTF-8"?>

<seqgramodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://kkrismer.github.io/seqgra/model-config.xsd">
	<general id="tf-mc2-dna150-conv2-lstm32-fc32-s1">
		<name>convolutation layer with 2 filter, LSTM layer with 32 units, fully connected layer with 32 nodes, two conditions</name>
		<description></description>
		<task>multi-class classification</task>
		<sequencespace>DNA</sequencespace>
		<library>TensorFlow</library>
		<labels>
			<label>c1</label>
			<label>c2</label>
		</labels>
		<seed>1</seed>
	</general>
	<architecture>
		<sequential>
			<operation input_shape="(150, 4)" kernel_size="5" filters="2" activation="relu" padding="same">Conv1D</operation>
			<operation target_shape="(150, 2)">Reshape</operation>
			<operation units="32">LSTM</operation>
			<operation units="32" activation="relu">Dense</operation>
			<operation units="2" activation="softmax">Dense</operation>
		</sequential>
	</architecture>
	<loss>
		<hyperparameter name="loss">categorical_crossentropy</hyperparameter>
	</loss>
	<optimizer>
		<hyperparameter name="optimizer">Adam</hyperparameter>
		<hyperparameter name="learning_rate">0.001</hyperparameter>
	</optimizer>
	<trainingprocess>
		<hyperparameter name="batch_size">32</hyperparameter>
		<hyperparameter name="epochs">100</hyperparameter>
		<hyperparameter name="early_stopping">True</hyperparameter>
		<hyperparameter name="shuffle">True</hyperparameter>
	</trainingprocess>
</seqgramodel>

=== gifford-lab/seqgra/docsrc/defs/md/torch-mc2-dna150-conv2-gmp-fc5-s1.xml
<?xml version="1.0" encoding="UTF-8"?>

<seqgramodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://kkrismer.github.io/seqgra/model-config.xsd">
	<general id="torch-mc2-dna150-conv2-gmp-fc5-s1">
		<name>1 conv layer with 2 11-nt wide filters, global max pooling, 1 fully connected layer with 5 units</name>
		<description></description>
		<task>multi-class classification</task>
		<sequencespace>DNA</sequencespace>
		<library>PyTorch</library>
		<inputencoding>1D</inputencoding>
		<labels>
			<label>c1</label>
			<label>c2</label>
		</labels>
		<seed>1</seed>
	</general>
	<architecture>
		<external format="pytorch-module" classname="TorchModel">PyTorch/o2-dna150-conv2-gmp-fc5.py</external>
	</architecture>
	<loss>
		<hyperparameter name="loss">CrossEntropyLoss</hyperparameter>
	</loss>
	<optimizer>
		<hyperparameter name="optimizer">SGD</hyperparameter>
		<hyperparameter name="learning_rate">0.001</hyperparameter>
		<hyperparameter name="momentum">0.9</hyperparameter>
	</optimizer>
	<trainingprocess>
		<hyperparameter name="batch_size">32</hyperparameter>
		<hyperparameter name="epochs">100</hyperparameter>
		<hyperparameter name="early_stopping">True</hyperparameter>
		<hyperparameter name="shuffle">True</hyperparameter>
	</trainingprocess>
</seqgramodel>

=== gifford-lab/seqgra/docs/md/tf-mc2-dna150-conv800-gmp-s1.xml
<?xml version="1.0" encoding="UTF-8"?>

<seqgramodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://kkrismer.github.io/seqgra/model-config.xsd">
	<general id="tf-mc2-dna150-conv800-gmp-s1">
		<name>convolutation layer with 800 filters, global max pooling, 2 conditions</name>
		<description></description>
		<task>multi-class classification</task>
		<sequencespace>DNA</sequencespace>
		<library>TensorFlow</library>
		<labels>
			<label>c1</label>
			<label>c2</label>
		</labels>
		<seed>1</seed>
	</general>
	<architecture>
		<sequential>
			<operation input_shape="(150, 4)" kernel_size="5" filters="800" activation="relu">Conv1D</operation>
			<operation>GlobalMaxPool1D</operation>
			<operation units="2" activation="softmax">Dense</operation>
		</sequential>
	</architecture>
	<loss>
		<hyperparameter name="loss">categorical_crossentropy</hyperparameter>
	</loss>
	<optimizer>
		<hyperparameter name="optimizer">Adam</hyperparameter>
		<hyperparameter name="learning_rate">0.001</hyperparameter>
	</optimizer>
	<trainingprocess>
		<hyperparameter name="batch_size">32</hyperparameter>
		<hyperparameter name="epochs">100</hyperparameter>
		<hyperparameter name="early_stopping">True</hyperparameter>
		<hyperparameter name="shuffle">True</hyperparameter>
	</trainingprocess>
</seqgramodel>

=== gifford-lab/seqgra/docsrc/defs/md/torch-ml2-dna1000-deepsea-s1.xml
<?xml version="1.0" encoding="UTF-8"?>

<seqgramodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://kkrismer.github.io/seqgra/model-config.xsd">
	<general id="torch-ml2-dna1000-deepsea-s1">
		<name>DeepSEA architecture</name>
		<description>1000 bp DNA sequence window, 3 convolutional layers, 1 fully connected layer</description>
		<task>multi-label classification</task>
		<sequencespace>DNA</sequencespace>
		<library>PyTorch</library>
		<labels>
			<label>c1</label>
			<label>c2</label>
		</labels>
		<seed>1</seed>
	</general>
	<architecture>
		<external format="pytorch-module" classname="TorchModel">PyTorch/o2-dna1000-deepsea.py</external>
	</architecture>
	<loss>
		<hyperparameter name="loss">BCEWithLogitsLoss</hyperparameter>
	</loss>
	<optimizer>
		<hyperparameter name="optimizer">SGD</hyperparameter>
		<hyperparameter name="learning_rate">0.01</hyperparameter>
		<hyperparameter name="momentum">0.9</hyperparameter>
	</optimizer>
	<trainingprocess>
		<hyperparameter name="batch_size">100</hyperparameter>
		<hyperparameter name="epochs">100</hyperparameter>
		<hyperparameter name="early_stopping">True</hyperparameter>
		<hyperparameter name="shuffle">True</hyperparameter>
	</trainingprocess>
</seqgramodel>

=== gifford-lab/seqgra/docsrc/defs/md/tf-mc10-dna1000-conv10-fc10-s0.xml
<?xml version="1.0" encoding="UTF-8"?>

<seqgramodel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://kkrismer.github.io/seqgra/model-config.xsd">
	<general id="tf-mc10-dna1000-conv10-fc10-s0">
		<name>1 conv layer with 10 11-nt wide filters, 1 fully connected layer with 10 units</name>
		<description></description>
		<task>multi-class classification</task>
		<sequencespace>DNA</sequencespace>
		<library>TensorFlow</library>
		<labels>
			<pattern prefix="c" postfix="" min="1" max="10"/>
		</labels>
		<seed>0</seed>
	</general>
	<architecture>
		<sequential>
			<operation input_shape="(1000, 4)" kernel_size="11" filters="10" activation="relu">Conv1D</operation>
			<operation>Flatten</operation>
			<operation units="10" activation="relu">Dense</operation>
			<operation units="10" activation="softmax">Dense</operation>
		</sequential>
	</architecture>
	<loss>
		<hyperparameter name="loss">categorical_crossentropy</hyperparameter>
	</loss>
	<optimizer>
		<hyperparameter name="optimizer">SGD</hyperparameter>
		<hyperparameter name="learning_rate">0.001</hyperparameter>
		<hyperparameter name="momentum">0.9</hyperparameter>
	</optimizer>
	<trainingprocess>
		<hyperparameter name="batch_size">32</hyperparameter>
		<hyperparameter name="epochs">100</hyperparameter>
		<hyperparameter name="early_stopping">True</hyperparameter>
		<hyperparameter name="shuffle">True</hyperparameter>
	</trainingprocess>
</seqgramodel>
